[theme]
primaryColor = "#3B82F6"                 # Warna aksen biru terang saat di-hover/pilih
backgroundColor = "#F8FAFC"              # Warna latar belakang halaman (putih-abu)
secondaryBackgroundColor = "#0A2540"     # Warna sidebar kiri (Biru Navy)
textColor = "#1E293B"                    # Warna teks utama
font = "sans serif"
